#!/bin/sh

# default image to run
IMAGE=${IMAGE:-quay.io/testing-farm/cli:latest}

# set no colors if NO_COLOR variable set
if [ -n "$NO_COLOR" ]; then
    SET_NO_COLOR="-e NO_COLOR=1"
fi

# check for podman
CONTAINER_RUNTIME=$(command -v podman || command -v docker)
if [ -z "$CONTAINER_RUNTIME" ]; then
    echo "⛔ No podman or docker not found. Container runtime is required for the tool."
    exit 255
fi

# if in git repository, volume mount it
if git rev-parse --git-dir &>/dev/null; then
    GIT_DIR=$(readlink -f $(git rev-parse --git-dir))
    MOUNT_GIT="-v ${GIT_DIR%.git}:/code:Z"
fi

# testing-farm image and wrapper update
if [ "$1" == "update" ]; then
    curl -Lo $(readlink -f $0) https://gitlab.com/testing-farm/cli/-/raw/main/container/testing-farm
    $CONTAINER_RUNTIME pull $IMAGE
    exit 0
fi

# mount $HOME/.ssh direcotry
if [ "$1" == "reserve" ]; then
    if grep -q -- '--ssh-public-key' <<< "$*"; then
        echo "Option '--ssh-public-key' is not supported with container installation. Use the default settings please."
        exit 255
    fi
    if [ -z "$SSH_AUTH_SOCK" -o ! -e "$SSH_AUTH_SOCK" ]; then
        echo "Could not detect a running ssh-agent, cannot continue."
        exit 255
    fi
    if [ ! -d "$HOME/.ssh" ]; then
        echo "SSH key directory '$HOME/.ssh' not found, cannot continue."
        exit 255
     fi

    # To share ssh agent, we need disable SELinux confinement
    # https://www.redhat.com/sysadmin/privileged-flag-container-engines
    MOUNT_SSH="-v $SSH_AUTH_SOCK:$SSH_AUTH_SOCK:Z -e SSH_AUTH_SOCK=$SSH_AUTH_SOCK --security-opt label=disable"

    # pubkeys will be appended to authorized_keys on VM
    for k in $HOME/.ssh/*.pub;do
        MOUNT_SSH+=" -v $k:/root/.ssh/$(basename $k):ro,Z"
    done
fi

# run the tool
$CONTAINER_RUNTIME run --network=host $SET_NO_COLOR -e TESTING_FARM_API_TOKEN=$TESTING_FARM_API_TOKEN --rm -it $MOUNT_GIT $MOUNT_SSH $IMAGE testing-farm "$@"
