#!/bin/sh

# default image to run
IMAGE=${IMAGE:-quay.io/testing-farm/cli:latest}

# set no colors if NO_COLOR variable set
if [ -n "$NO_COLOR" ]; then
    SET_NO_COLOR="-e NO_COLOR=1"
fi

# check for podman
CONTAINER_RUNTIME=$(command -v podman || command -v docker)
if [ -z "$CONTAINER_RUNTIME" ]; then
    echo "⛔ No podman or docker not found. Container runtime is required for the tool."
    exit 255
fi

# if in git repository, volume mount it
if git rev-parse --git-dir &>/dev/null; then
    GIT_DIR=$(readlink -f $(git rev-parse --git-dir))
    MOUNT_GIT="-v ${GIT_DIR%.git}:/code:Z"
fi

# testing-farm image and wrapper update
if [ "$1" == "update" ]; then
    curl -Lo $(readlink -f $0) https://gitlab.com/testing-farm/cli/-/raw/main/container/testing-farm
    $CONTAINER_RUNTIME pull $IMAGE
    exit 0
fi

# mount SSH public keys in case of reservations
if [ "$1" == "reserve" ]; then
    if grep -q -- '--ssh-public-key' <<< "$*"; then
        echo "Option '--ssh-public-key' is not supported with container installation. Use the default settings please."
        exit 255
    fi
    if [ -z "$SSH_AUTH_SOCK" -o ! -e "$SSH_AUTH_SOCK" ]; then
        echo "Could not detect a running ssh-agent, cannot continue."
        exit 255
    fi
    if [ ! -d "$HOME/.ssh" ]; then
        echo "SSH key directory '$HOME/.ssh' not found, cannot continue."
        exit 255
     fi

    # To share ssh agent, we need disable SELinux confinement
    # https://www.redhat.com/sysadmin/privileged-flag-container-engines
    MOUNT_SSH="-v $SSH_AUTH_SOCK:$SSH_AUTH_SOCK:Z -e SSH_AUTH_SOCK=$SSH_AUTH_SOCK --security-opt label=disable"

    # pubkeys will be appended to authorized_keys on VM
    for k in $HOME/.ssh/*.pub;do
        MOUNT_SSH+=" -v $k:/root/.ssh/$(basename $k):ro,Z"
    done
fi

# mount CA certificates from the system, works only on RHEL-like systems for now
SYSTEM_CA_PATH="/etc/ssl/certs/ca-bundle.crt"
ALPINE_CA_PATH="/etc/ssl/certs/ca-certificates.crt"
if [ -e "$SYSTEM_CA_PATH" ]; then
    # we need a copy of the file to be able to volume mount it
    TEMP_CA_FILE=$(mktemp)
    cp -f "$(readlink -f $SYSTEM_CA_PATH)" "$TEMP_CA_FILE"

    # make sure to remove the temporary file after execution
    trap 'rm -f $TEMP_CA_FILE' EXIT

    # mount to Alpine's standard path for CA certificates
    MOUNT_CA="-v $TEMP_CA_FILE:$ALPINE_CA_PATH:ro,Z"
fi

# allocate a pseudo-TTY for container if NO_TTY unset
TTY="-t"
if [ ! -z "$NO_TTY" ]; then
    TTY=""
fi

$CONTAINER_RUNTIME run \
    --rm \
    --interactive \
    --network=host $SET_NO_COLOR \
    --env TESTING_FARM_API_TOKEN=$TESTING_FARM_API_TOKEN \
    --env REQUESTS_CA_BUNDLE=$ALPINE_CA_PATH \
    $TTY \
    $MOUNT_GIT \
    $MOUNT_SSH \
    $MOUNT_CA \
    $IMAGE testing-farm "$@"
